services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8106:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    depends_on:
      - api

  api:
    build:
      context: api
    restart: unless-stopped
    env_file: .env
