version: '3.8'
services:
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Port pour Vite

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Port pour Ktor
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: gilles
      DB_PASSWORD: password
      DB_NAME: gilles_db
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: gilles
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gilles_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
