# Generated by Django 4.2.6 on 2023-10-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='projets/')),
                ('langages', models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('PHP', 'PHP'), ('PYTHON', 'Python'), ('DJANGO', 'Django'), ('DART', 'Dart'), ('ANGULAR', 'Angular'), ('BOOTSTRAP', 'Bootstrap')], max_length=10)),
                ('liens', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
