# Generated by Django 4.2.6 on 2023-10-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='projet',
            name='langages',
        ),
        migrations.AddField(
            model_name='projet',
            name='langages',
            field=models.ManyToManyField(to='gh.langage'),
        ),
    ]
