# Generated by Django 4.2.6 on 2023-10-17 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gh', '0002_langage_remove_projet_langages_projet_langages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='liens',
        ),
        migrations.CreateModel(
            name='Lien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens', to='gh.projet')),
            ],
        ),
    ]
