# Generated by Django 4.2.7 on 2024-01-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh', '0017_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
