# Generated by Django 4.2.6 on 2023-10-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh', '0003_remove_projet_liens_lien'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
