# Generated by Django 4.2.6 on 2023-10-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh', '0004_projet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='annee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
