# Generated by Django 4.2.7 on 2023-11-07 10:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gh', '0007_imageprojet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
