# Generated by Django 4.2.7 on 2024-01-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh', '0012_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description_courte',
            field=models.CharField(default='null', max_length=350),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
