# Generated by Django 4.2.7 on 2024-01-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh', '0013_alter_article_description_courte_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visibility',
            field=models.CharField(choices=[('draft', 'Draft'), ('public', 'Public'), ('private', 'Private')], default='defaut', max_length=30),
            preserve_default=False,
        ),
    ]
