# Generated by Django 4.2.7 on 2024-01-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh', '0015_alter_article_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='langage',
            field=models.ManyToManyField(
                blank=True, to='gh.langage', verbose_name='Langages'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='langage',
            name='nom',
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True),
        ),
    ]
