# Generated by Django 4.2.7 on 2024-01-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh', '0016_article_langage_article_slug_alter_langage_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
